name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/kivy/buildozer:latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Fix Safe Directory
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Compile APK Inside Clean Docker
      run: |
        printf 'y\n' | buildozer -v android debug

    - name: Upload Finished APK
      uses: actions/upload-artifact@v4
      with:
        name: BARAT-Core-APK
        path: bin/*.apk
